easy_admin:
    site_name: 'SK-storage'
    list:
        actions: ['show', 'delete', 'edit', 'new', 'search']
    edit:
        actions: ['show', 'delete', 'list']
    design:
        menu:
            - { entity: 'User', permission: 'ROLE_SUPER_ADMIN' }
            - Project
            - Account
            - MonitoringTask
    entities:
        User:
            class: App\Entity\User
            password_encoding: { algorithm: 'auto'}
            new:
                fields:
                    - email
                    - firstname
                    - lastname
                    - { property: 'plainPassword', type: 'password' }
                    - { property: 'roles', type: 'choice', type_options: { multiple: true, choices: { 'ROLE_USER': 'ROLE_USER', 'ROLE_ADMIN': 'ROLE_ADMIN', 'ROLE_SUPER_ADMIN': 'ROLE_SUPER_ADMIN' } } }
            edit:
                fields:
                    - email
                    - firstname
                    - lastname
                    - { property: 'plainPassword', type: 'password' }
                    - { property: 'roles', type: 'choice', type_options: { multiple: true, choices: { 'ROLE_USER': 'ROLE_USER', 'ROLE_ADMIN': 'ROLE_ADMIN', 'ROLE_SUPER_ADMIN': 'ROLE_SUPER_ADMIN' } } }
            list:
                fields:
                    - email
                    - firstname
                    - lastname
        Project:
            class: App\Entity\Project
            new:
                fields:
                    - title
                    - description
            edit:
                fields:
                    - title
                    - description
            list:
                fields:
                    - title
                    - description
            show:
                fields:
                    - title
                    - description
                    - accounts
        Account:
            class: App\Entity\Account
            new:
                fields:
                    - title
                    - tag
                    - login
                    - password
                    - link
                    - extraData
                    - project
                    - description
                    - users
            edit:
                fields:
                    - title
                    - tag
                    - login
                    - password
                    - link
                    - extraData
                    - description
                    - users
            list:
                fields:
                    - project
                    - title
                    - tag
                    - link
            show:
                fields:
                    - title
                    - tag
                    - login
                    - password
                    - link
                    - extraData
                    - project
                    - description
                    - users
        MonitoringTask:
            class: App\Entity\MonitoringTask
            new:
                fields:
                    - project
                    - url
                    - { property: 'requestMethod', type: 'choice', type_options: { multiple: false, choices: { 'GET': 'GET', 'POST': 'POST', 'PATH': 'PATH', 'PUT': 'PUT', 'DELETE': 'DELETE' } } }
                    - expectedResponseCode
                    - expectedResponseBody
                    - checkIntervalSeconds
            edit:
                fields:
                    - url
                    - { property: 'requestMethod', type: 'choice', type_options: { multiple: false, choices: { 'GET': 'GET', 'POST': 'POST', 'PATH': 'PATH', 'PUT': 'PUT', 'DELETE': 'DELETE' } } }
                    - expectedResponseCode
                    - expectedResponseBody
                    - checkIntervalSeconds
            list:
                fields:
                    - id
                    - project
                    - url
                    - requestMethod
                    - checkIntervalSeconds
            show:
                fields:
                    - id
                    - url
                    - requestMethod
                    - expectedResponseCode
                    - expectedResponseBody
                    - checkIntervalSeconds