parameters:
    proxy_url: '%env(PROXY_URL)%'

services:
    _defaults:
        autowire: true
        autoconfigure: true
        bind:
            $proxyUrl: '%proxy_url%'

    App\:
        resource: '../src/*'
        exclude: '../src/{DependencyInjection,Entity,Migrations,Tests,Kernel.php}'

    App\Controller\:
        resource: '../src/Controller'
        tags: ['controller.service_arguments']
